dailyIE/dailyIE/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('',include('income.urls')),
    path('',include('expense.urls')),
]

dailyIE/expense/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addexpense',v.addexpense1),
    path('expenselist',v.data2,name='list'),
    path('deleteE/<int:id>',v.delete_E),
    path('editE/<int:id>',v.edit_E),
    path('expense_search',v.expense_search2,name='expense_search'),
    path('extp/<str:ext>',v.sort_data,name='ext'),
    path('pay',v.payment1),

]

dailyIE/income/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inc',v.addincome2),
    path('incomelist',v.data1,name='ilist'),
    path('delete1/<int:id>',v.delete_emp),
    path('edit/<int:id>',v.edit1),
    path('income_search',v.income_search2,name='income_search'),
    path('ixtp/<str:ixt>',v.sort_data1,name='ixt'),
]

dailyIE/expense/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField()
    description=models.TextField(max_length=30)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table='Expense'


from django import forms

class ExpenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'



class Payment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    amount=models.FloatField()
    razorpay_id=models.CharField(max_length=100,blank=True,null=True)
    razorpay_payment_status=models.CharField(max_length=100,blank=True,null=True)
    razorpay_payment_id=models.CharField(max_length=100,blank=True,null=True)
    paid=models.BooleanField(default=False)

dailyIE/expense/views.py
from django.shortcuts import render,redirect
from .models import ExpenseForm,Expense
from django.contrib.auth.models import User

# Create your views here.
def addexpense1(request):
    uid=request.session.get('uid')

    if request.method=='POST':
        expense=request.POST.get('expense')
        if get_balance(request) > int(expense): 
              #coverting the string into int
              expense_type=request.POST.get('expense_type')
              expense=request.POST.get('expense')
              expense_type=request.POST.get('expense_type')
              expense_date=request.POST.get('expense_date')
              description=request.POST.get('description')
              inc=Expense()
              inc.expense=expense
              inc.expense_type=expense_type
              inc.expense_date=expense_date
              inc.description=description
              inc.user=User.objects.get(id=uid)
              inc.save()
              return redirect('/')
        
        else:
            f=ExpenseForm
            y={'k':f,'exp_msg':'Warning : In-sufficient balance !!!'}
            return render(request,"addexpense1.html",y)

    else:
        f=ExpenseForm
        y={'k':f}
        return render(request,"addexpense1.html",y)
    
    # if request.method=='POST':
    #     f=ExpenseForm(request.POST)
    #     f.save()
    #     return redirect('/')

    # else:
    #     f=ExpenseForm
    #     o={'w':f}
    #     return render(request,'addexpense1.html',o)
    
from .models import Expense

def data2(request):
    uid=request.session.get('uid')
    elist=Expense.objects.filter(user=uid)       #object is the manager for emp and for all the data of all users. user will be assigned uid i.e user=uid
    expt=set()
    for i in elist:
        expt.add(i.expense_type)

    d={'s':elist,'expt':expt}                    # s has all the data
    return render(request,'db3.html',d) 


    # elist=Expense.objects.all()   #object is the manager for emp and "all" means retrieving all fields

    # ue={'u':elist}
    # return render(request,'db3.html',ue)


def delete_E(request,id):
    x=Expense.objects.get(id=id)
    x.delete()
    return redirect('/expenselist')


def edit_E(request,id):
    me=Expense.objects.get(id=id)
    if request.method=='POST':
        f=ExpenseForm(request.POST,instance=me)  
        f.save()
        return redirect('/')
    
    else:
        fe=ExpenseForm(instance=me)
        contexts={'s':fe}
        return render(request,"addexpense1.html",contexts)
    

    #django modelform is a helper model that create a html page by using model
    # we pass the context in the render, our key goes through the context4


def expense_search2(request):
    uid=request.session.get('uid')
    srch=request.POST.get('srch')
    expl=Expense.objects.filter(user=uid,description__icontains=srch)
    context={'s':expl}
    return render(request,"db3.html",context)


def sort_data(request,ext):
    uid=request.session.get('uid')
    elist=Expense.objects.filter(user=uid)   
    expt=set()
    for i in elist:
        expt.add(i.expense_type)

    elist=Expense.objects.filter(user=uid,expense_type=ext) # to filter category wise

    d={'s':elist,'expt':expt}                # s has all the data
    return render(request,'db3.html',d) 


from income.models import Income
from expense.models import Expense
def get_balance(request):
    uid=request.session.get('uid')  
    incl=Income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)

    total_income=0
    total_expense=0

    for i in incl:
        total_income=total_income + i.income
      

    for i in expl:
        total_expense=total_expense + i.expense

    return total_income - total_expense

from .models import Payment

import razorpay
from django.conf import settings

def payment1(request):
    user=request.user
    client = razorpay.Client(auth=(settings.RAZOR_KEY_ID,settings.RAZOR_KEY_SECRET))

    DATA={'amount':50000,'currency':'INR','receipt':'receipt#1'}
    payment_response=client.order.create(data=DATA)
    print(payment_response)
    id=payment_response['id']
    status=payment_response['status']
    if status == 'created':
        payment=Payment(
            user=user,
            razorpay_id=id,
            razorpay_payment_status=status
            
        )
        payment.save()
    return render(request,'payment.html')

# def get(self,request):
#         totalitem=0
#         wishitem=0
#         if request.user.is_authenticated:
#             totalitem=len(Cart.objects.filter(user=request.user))
#             wishitem=len(Wishlist.objects.filter(user=request.user))
#         user=request.user
#         add=Customer.objects.filter(user=user)
#         cart_items=Cart.objects.filter(user=user)
#         famount=0
#         for p in cart_items:
#             value = p.quantity * p.product.discounted_price
#             famount=famount+value
#         totalamount=famount+40
#         razoramount=int(totalamount*100)
#         client =razorpay.Client(auth=(settings.RAZOR_KEY_ID,settings.RAZOR_KEY_SECRET))
#         data ={'amount':razoramount,'currency':'INR','receipt':'order_rcptid_12'}
#         payment_response=client.order.create(data=data)
#         print(payment_response)
#         # {'id': 'order_MjJ3eHbbvGINOk', 'entity': 'order', 'amount': 49000, 'amount_paid': 0, 'amount_due': 49000, 'currency': 'INR', 'receipt': 'order_rcptid_12', 'offer_id': None, 'status': 'created', 'attempts': 0, 'notes': [], 'created_at': 1696242726}
#         order_id =payment_response['id']
#         order_status =payment_response['status']
       
#         if order_status =='created':
#             payment = Payment(
#                 user=user,
#                 amount=totalamount,
#                 razorpay_order_id=order_id,
#                 razorpay_payment_status=order_status
#             )
#             payment.save()
#         return render(request,'checkout.html',locals())
 

    

dailyIE/expense/templates/addexpense1.html
{%extends 'sidebar.html'%}
{%block body%}


<h2 class="addin">ADD EXPENSE:-</h2>
<h2 style="color: red;">{{exp_msg}}</h2>
<style>
  tr:hover{
    background-color: khaki;
  }

  .addin{
    background-color: rgb(255, 136, 0);
    width: 180px;
    border: solid 5px black;
    border-radius: 5px;
    padding: 5px;
    font-size: 20px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }


</style>


<form method="post">
  {% csrf_token %}
  <table border="2" style="border: solid 5px darkred;">
    <tr>
      <th><label for="id_expense">Expense:</label></th>
      <td>
        <input type="number" name="expense" required id="id_expense" />
      </td>
    </tr>

    <tr>
      <th><label for="id_expense_type">Expense type:</label></th>
      <td>
        <input
          type="text"
          name="expense_type"
          maxlength="30"
          required
          id="id_expense_type"
        />
      </td>
    </tr>

    <tr>
      <th><label for="id_expense_date">Expense date:</label></th>
      <td>
        <input type="text" name="expense_date" required id="id_expense_date" />
      </td>
    </tr>

    <tr>
      <th><label for="id_description">Description:</label></th>
      <td>
        <textarea
          name="description"
          cols="40"
          rows="10"
          maxlength="300"
          required
          id="id_description"
        ></textarea>
      </td>
    </tr>

    <tr>
      <th><label for="id_user">User:</label></th>
      <td><input type="text" name="uid" value="{{user}}" /></td>
    </tr>

    <tr>
      <td><input type="submit" name="submit" id="" /></td>
      <td><input type="reset" value="reset" id="" /></td>
    </tr>
  </table>
</form>
{%endblock%}


dailyIE/expense/templates/db3.html
{%extends 'sidebar.html'%}
{%block body%}

<script src="https://kit.fontawesome.com/5c3b24e338.js" crossorigin="anonymous"></script>
{%load static%}
    <link rel="stylesheet" href="{%static 'css/expenselist.css'%}">

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>


<form method="post" action="{% url 'expense_search' %}">
    {%csrf_token%}
    <span class="income"><b>Expense List:-</b></span>
    <textarea name="srch" id="search11" cols="30" rows="2" placeholder="search here " ></textarea>

    <button id="icon"><i class="fa-solid fa-magnifying-glass"></i></button>
</form>


<table border="5" cellspacing='10' style="border: solid 5px darkred;" class="tab" >
    <tr>
    
    <th>ID</th>
    <th>Expense</th>
    <th>Expense_type</th>
    <th>Expense_date</th>
    <th>Description</th>
    <th>User id</th>
    <th colspan="3">Action</th>
   

</tr>
<!-- i will get the whole data from el -->
{%for i in s%} 


    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expense_type}}</td>
        <td>{{i.expense_date}}</td>
        <td><textarea name="" id="" cols="15" rows="2">{{i.description}}</textarea></td>
        <td>{{i.user}}</td>
        <td class="del"><a href="deleteE/{{i.id}}">delete</a></td>
        <td class="edi"><a href="editE/{{i.id}}">edit</a></td>
        <td class="pay1"><a href="pay">pay</a></td>
    </tr>
{%endfor%}


</table>

<div class="rside">
    <p class="categ"><b>CATEGORIES:-</b></p>
    <h2><a href="{%url 'list' %}">All</a></h2>
    {%for i in expt%}
    <h2><a href="{%url 'ext' i%}">{{i}}</a></h2>
    {%endfor%}
</div>

{%endblock%}

dailyIE/expense/templates/payment.html
<button id="rzp-button1">Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_npe0UzHqDMQBYM", // Enter the Key ID generated from the Dashboard
    "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Daily Income-Expense Management System", //your business name
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "order_9A33XWu170gUtm", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
      /*  alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)*/
    },
    /*"prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information, especially their phone number
        "name": "Savio Johnson", //your customer's name
        "email": "saviojohnson700@gmail.com", 
        "contact": "9082921105"  //Provide the customer's phone number for better conversion rates 
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },*/
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
       // alert(response.error.code);
        alert(response.error.description);
       /* alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);*/
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>