dailyIE/dailyIE/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('',include('income.urls')),
    path('',include('expense.urls')),
]

dailyIE/income/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inc',v.addincome2),
    path('incomelist',v.data1,name='ilist'),
    path('delete1/<int:id>',v.delete_emp),
    path('edit/<int:id>',v.edit1),
    path('income_search',v.income_search2,name='income_search'),
    path('ixtp/<str:ixt>',v.sort_data1,name='ixt'),
]

dailyIE/income/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=30)
    user=models.ForeignKey(User,on_delete=models.CASCADE)


    class Meta:
        db_table='Income'


    
   

from django import forms

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

    def __str__(self):
        return self.name




    

dailyIE/income/views.py
from django.shortcuts import render,redirect
from .models import IncomeForm,Income
from django.contrib.auth.models import User
# Create your views here.


def addincome2(request):
    uid=request.session.get('uid')
    if request.method=='POST':
        income=request.POST.get('income')
        income_type=request.POST.get('income_type')
        income_date=request.POST.get('income_date')
        description=request.POST.get('description')
        incs=Income()
        incs.income=income
        incs.income_type=income_type
        incs.income_date=income_date
        incs.description=description
        incs.user=User.objects.get(id=uid)
        incs.save()
        return redirect('/')

    else:
        f=IncomeForm
        y={'h':f}
        return render(request,"addincome1.html",y)
    


# def data1(request):
#     uid=request.session.get('uid')
#     elist=Income.objects.filter(user=uid)   #object is the manager for emp and for all the data of all users. user will be assigned uid i.e user=uid
#     d={'s':elist}
#     return render(request,'dbb.html',d)

def data1(request):
    uid=request.session.get('uid')
    elist=Income.objects.filter(user=uid)       #object is the manager for emp and for all the data of all users. user will be assigned uid i.e user=uid
    ixpt=set()
    for i in elist:
        ixpt.add(i.income_type)

    d={'s':elist,'ixpt':ixpt}                    # s has all the data
    return render(request,'dbb.html',d) 


def delete_emp(request,id):
    x=Income.objects.get(id=id)
    x.delete()
    return redirect('/incomelist')


def edit1(request,id):
    m=Income.objects.get(id=id)
    if request.method=='POST':
        f=IncomeForm(request.POST,instance=m)  
        f.save()
        return redirect('/incomelist')
    
    else:
        f=IncomeForm(instance=m)
        context={'s':f}
        return render(request,"addincome1.html",context)
    



def income_search2(request):
    uid=request.session.get('uid')
    srch=request.POST.get('srchs')
    expl=Income.objects.filter(user=uid,description__icontains=srch)
    context={'s':expl}
    return render(request,"dbb.html",context)


def sort_data1(request,ixt):
    uid=request.session.get('uid')
    elist=Income.objects.filter(user=uid)   
    ixpt=set()
    for i in elist:
        ixpt.add(i.income_type)

    elist=Income.objects.filter(user=uid,income_type=ixt) # to filter category wise

    d={'s':elist,'ixpt':ixpt}                # s has all the data
    return render(request,'dbb.html',d) 

dailyIE/income/templates/addincome1.html
{%extends 'sidebar.html'%}
{%block body%}

<h2 class="addin">ADD INCOME:-</h2>

<style>
  tr:hover{
    background-color: khaki;
  }

  .addin{
    background-color: greenyellow;
    width: 180px;
    border: solid 5px black;
    border-radius: 5px;
    padding: 5px;
    font-size: 20px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }


</style>

<form method="post">
  {% csrf_token %}

  <table border="2" style="border: solid 5px darkred;" >
    <tr>
      <th><label for="id_income">Income:</label></th>
      <td>
        <input type="number" name="income" required id="id_income" />
      </td>
    </tr>

    <tr>
      <th><label for="id_income_type">Income type:</label></th>
      <td>
        <input
          type="text"
          name="income_type"
          maxlength="30"
          required
          id="id_income_type"
        />
      </td>
    </tr>

    <tr>
      <th><label for="id_income_date">Income date:</label></th>
      <td>
        <input type="text" name="income_date" required id="id_income_date" />
      </td>
    </tr>

    <tr>
      <th><label for="id_description">Description:</label></th>
      <td>
        <textarea
          name="description"
          cols="40"
          rows="10"
          maxlength="300"
          required
          id="id_description"
        ></textarea>
      </td>
    </tr>

    <tr>
      <th><label for="id_user">User:</label></th>
      <td><input type="text" name="uid" value="{{user}}" /></td>
    </tr>

    <tr>
      <td><input type="submit" name="submit" id="" /></td>
      <td><input type="reset" value="reset" id="" /></td>
    </tr>
  </table>
</form>
{%endblock%}

dailyIE/income/templates/dbb.html
{%extends 'sidebar.html'%}
{%block body%}

<script src="https://kit.fontawesome.com/5c3b24e338.js" crossorigin="anonymous"></script>
{%load static%}
    <link rel="stylesheet" href="{%static 'css/incomelist.css'%}">

<form method="post" action="{% url 'income_search' %}">
    
    {%csrf_token%}
    <span class="income"><b>Income List:-</b></span>
    <textarea name="srchs" id="search11" cols="30" rows="2" placeholder="search here " ></textarea>

    <button id="icon"><i class="fa-solid fa-magnifying-glass"></i></button>
</form>


   
</style>
{%if s%}
<table border="5" cellspacing='15' style="border: solid 5px darkred;" >
    <tr>
    <th>ID</th>
    <th>Income</th>
    <th>Income_type</th>
    <th>Income_date</th>
    <th>Description</th>
    <th>User ID</th>
    <th colspan="2">Action</th>
   

</tr>
<!-- i will get the whole data from el -->
{%for i in s%} 
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.income_date}}</td>
        <!-- <td><textarea name="" id="" cols="10" rows="2">{{i.description}}</textarea></td> -->
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td class="del"><a href="delete1/{{i.id}}">delete</a></td> 
        <!-- delete jab jayga id bhi saat mein lekhar jayga -->
        <td class="edi"><a href="edit/{{i.user.id}}">edit</a></td>
    </tr>
{%endfor%}

</table>
{%else%}
<h1>No Record Found.....</h1>
{%endif%}


<div class="iside">
    <p class="categ"><b>CATEGORIES:-</b></p>
    <h2><a href="{%url 'ilist' %}">All</a></h2>
    {%for i in ixpt%}
    <h2><a href="{%url 'ixt' i%}" >{{i}}</a></h2>
    
    {%endfor%}
</div>

{%endblock%}